package ai.tegmentum.webassembly4j.runtime;

import ai.tegmentum.webassembly4j.runtime.annotation.WasmExport;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Tests for String and byte[] marshalling through the proxy path.
 *
 * <p>These tests use a hand-crafted WASM module that exports:
 * <ul>
 *   <li>{@code memory} — 1 page of linear memory</li>
 *   <li>{@code cabi_realloc(old_ptr, old_size, align, new_size) -> new_ptr} — bump allocator</li>
 *   <li>{@code echo_string(retptr, ptr, len)} — copies string and writes (ptr, len) to retptr</li>
 *   <li>{@code echo_bytes(retptr, ptr, len)} — copies bytes and writes (ptr, len) to retptr</li>
 *   <li>{@code string_length(ptr, len) -> i32} — returns the byte length of the string</li>
 * </ul>
 */
class WasmRuntimeMarshalTest {

    /**
     * Hand-crafted WASM module with memory, cabi_realloc, and echo functions.
     *
     * WAT equivalent:
     * <pre>
     * (module
     *   (memory (export "memory") 1)
     *   ;; Global for bump allocator, starts at 1024 to avoid stomping on test data
     *   (global $bump (mut i32) (i32.const 1024))
     *
     *   ;; cabi_realloc: simple bump allocator
     *   (func (export "cabi_realloc") (param $old_ptr i32) (param $old_size i32)
     *         (param $align i32) (param $new_size i32) (result i32)
     *     (local $ptr i32)
     *     ;; Align bump pointer: ptr = (bump + align - 1) & ~(align - 1)
     *     (local.set $ptr
     *       (i32.and
     *         (i32.add (global.get $bump) (i32.sub (local.get $align) (i32.const 1)))
     *         (i32.xor (i32.sub (local.get $align) (i32.const 1)) (i32.const -1))))
     *     ;; bump = ptr + new_size
     *     (global.set $bump (i32.add (local.get $ptr) (local.get $new_size)))
     *     (local.get $ptr))
     *
     *   ;; echo_string: copies input data to new alloc, writes (ptr, len) at retptr
     *   (func (export "echo_string") (param $retptr i32) (param $ptr i32) (param $len i32)
     *     (local $dst i32)
     *     ;; Allocate space for the copy
     *     (local.set $dst
     *       (call $cabi_realloc_internal (i32.const 0) (i32.const 0) (i32.const 1) (local.get $len)))
     *     ;; memory.copy dst, src, len
     *     (memory.copy (local.get $dst) (local.get $ptr) (local.get $len))
     *     ;; Write ptr at retptr
     *     (i32.store (local.get $retptr) (local.get $dst))
     *     ;; Write len at retptr+4
     *     (i32.store offset=4 (local.get $retptr) (local.get $len)))
     *
     *   ;; echo_bytes: same as echo_string
     *   (func (export "echo_bytes") (param $retptr i32) (param $ptr i32) (param $len i32)
     *     (local $dst i32)
     *     (local.set $dst
     *       (call $cabi_realloc_internal (i32.const 0) (i32.const 0) (i32.const 1) (local.get $len)))
     *     (memory.copy (local.get $dst) (local.get $ptr) (local.get $len))
     *     (i32.store (local.get $retptr) (local.get $dst))
     *     (i32.store offset=4 (local.get $retptr) (local.get $len)))
     *
     *   ;; string_length: returns the byte length
     *   (func (export "string_length") (param $ptr i32) (param $len i32) (result i32)
     *     (local.get $len))
     *
     *   ;; Internal version of cabi_realloc for calls within the module
     *   (func $cabi_realloc_internal (param $old_ptr i32) (param $old_size i32)
     *         (param $align i32) (param $new_size i32) (result i32)
     *     (local $ptr i32)
     *     (local.set $ptr
     *       (i32.and
     *         (i32.add (global.get $bump) (i32.sub (local.get $align) (i32.const 1)))
     *         (i32.xor (i32.sub (local.get $align) (i32.const 1)) (i32.const -1))))
     *     (global.set $bump (i32.add (local.get $ptr) (local.get $new_size)))
     *     (local.get $ptr))
     * )
     * </pre>
     */
    // Generated by wat2wasm from the WAT in the comment above
    private static final byte[] MARSHAL_MODULE = {
        (byte) 0x00, (byte) 0x61, (byte) 0x73, (byte) 0x6d, (byte) 0x01, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x01, (byte) 0x15, (byte) 0x03, (byte) 0x60,
        (byte) 0x04, (byte) 0x7f, (byte) 0x7f, (byte) 0x7f, (byte) 0x7f, (byte) 0x01, (byte) 0x7f, (byte) 0x60, (byte) 0x03, (byte) 0x7f, (byte) 0x7f, (byte) 0x7f,
        (byte) 0x00, (byte) 0x60, (byte) 0x02, (byte) 0x7f, (byte) 0x7f, (byte) 0x01, (byte) 0x7f, (byte) 0x03, (byte) 0x06, (byte) 0x05, (byte) 0x00, (byte) 0x01,
        (byte) 0x01, (byte) 0x02, (byte) 0x00, (byte) 0x05, (byte) 0x03, (byte) 0x01, (byte) 0x00, (byte) 0x01, (byte) 0x06, (byte) 0x07, (byte) 0x01, (byte) 0x7f,
        (byte) 0x01, (byte) 0x41, (byte) 0x80, (byte) 0x08, (byte) 0x0b, (byte) 0x07, (byte) 0x44, (byte) 0x05, (byte) 0x06, (byte) 0x6d, (byte) 0x65, (byte) 0x6d,
        (byte) 0x6f, (byte) 0x72, (byte) 0x79, (byte) 0x02, (byte) 0x00, (byte) 0x0c, (byte) 0x63, (byte) 0x61, (byte) 0x62, (byte) 0x69, (byte) 0x5f, (byte) 0x72,
        (byte) 0x65, (byte) 0x61, (byte) 0x6c, (byte) 0x6c, (byte) 0x6f, (byte) 0x63, (byte) 0x00, (byte) 0x00, (byte) 0x0b, (byte) 0x65, (byte) 0x63, (byte) 0x68,
        (byte) 0x6f, (byte) 0x5f, (byte) 0x73, (byte) 0x74, (byte) 0x72, (byte) 0x69, (byte) 0x6e, (byte) 0x67, (byte) 0x00, (byte) 0x01, (byte) 0x0a, (byte) 0x65,
        (byte) 0x63, (byte) 0x68, (byte) 0x6f, (byte) 0x5f, (byte) 0x62, (byte) 0x79, (byte) 0x74, (byte) 0x65, (byte) 0x73, (byte) 0x00, (byte) 0x02, (byte) 0x0d,
        (byte) 0x73, (byte) 0x74, (byte) 0x72, (byte) 0x69, (byte) 0x6e, (byte) 0x67, (byte) 0x5f, (byte) 0x6c, (byte) 0x65, (byte) 0x6e, (byte) 0x67, (byte) 0x74,
        (byte) 0x68, (byte) 0x00, (byte) 0x03, (byte) 0x0a, (byte) 0x9a, (byte) 0x01, (byte) 0x05, (byte) 0x20, (byte) 0x01, (byte) 0x01, (byte) 0x7f, (byte) 0x23,
        (byte) 0x00, (byte) 0x20, (byte) 0x02, (byte) 0x41, (byte) 0x01, (byte) 0x6b, (byte) 0x6a, (byte) 0x20, (byte) 0x02, (byte) 0x41, (byte) 0x01, (byte) 0x6b,
        (byte) 0x41, (byte) 0x7f, (byte) 0x73, (byte) 0x71, (byte) 0x21, (byte) 0x04, (byte) 0x20, (byte) 0x04, (byte) 0x20, (byte) 0x03, (byte) 0x6a, (byte) 0x24,
        (byte) 0x00, (byte) 0x20, (byte) 0x04, (byte) 0x0b, (byte) 0x28, (byte) 0x01, (byte) 0x01, (byte) 0x7f, (byte) 0x41, (byte) 0x00, (byte) 0x41, (byte) 0x00,
        (byte) 0x41, (byte) 0x01, (byte) 0x20, (byte) 0x02, (byte) 0x10, (byte) 0x04, (byte) 0x21, (byte) 0x03, (byte) 0x20, (byte) 0x03, (byte) 0x20, (byte) 0x01,
        (byte) 0x20, (byte) 0x02, (byte) 0xfc, (byte) 0x0a, (byte) 0x00, (byte) 0x00, (byte) 0x20, (byte) 0x00, (byte) 0x20, (byte) 0x03, (byte) 0x36, (byte) 0x02,
        (byte) 0x00, (byte) 0x20, (byte) 0x00, (byte) 0x20, (byte) 0x02, (byte) 0x36, (byte) 0x02, (byte) 0x04, (byte) 0x0b, (byte) 0x28, (byte) 0x01, (byte) 0x01,
        (byte) 0x7f, (byte) 0x41, (byte) 0x00, (byte) 0x41, (byte) 0x00, (byte) 0x41, (byte) 0x01, (byte) 0x20, (byte) 0x02, (byte) 0x10, (byte) 0x04, (byte) 0x21,
        (byte) 0x03, (byte) 0x20, (byte) 0x03, (byte) 0x20, (byte) 0x01, (byte) 0x20, (byte) 0x02, (byte) 0xfc, (byte) 0x0a, (byte) 0x00, (byte) 0x00, (byte) 0x20,
        (byte) 0x00, (byte) 0x20, (byte) 0x03, (byte) 0x36, (byte) 0x02, (byte) 0x00, (byte) 0x20, (byte) 0x00, (byte) 0x20, (byte) 0x02, (byte) 0x36, (byte) 0x02,
        (byte) 0x04, (byte) 0x0b, (byte) 0x04, (byte) 0x00, (byte) 0x20, (byte) 0x01, (byte) 0x0b, (byte) 0x20, (byte) 0x01, (byte) 0x01, (byte) 0x7f, (byte) 0x23,
        (byte) 0x00, (byte) 0x20, (byte) 0x02, (byte) 0x41, (byte) 0x01, (byte) 0x6b, (byte) 0x6a, (byte) 0x20, (byte) 0x02, (byte) 0x41, (byte) 0x01, (byte) 0x6b,
        (byte) 0x41, (byte) 0x7f, (byte) 0x73, (byte) 0x71, (byte) 0x21, (byte) 0x04, (byte) 0x20, (byte) 0x04, (byte) 0x20, (byte) 0x03, (byte) 0x6a, (byte) 0x24,
        (byte) 0x00, (byte) 0x20, (byte) 0x04, (byte) 0x0b
    };

    interface Greeter extends AutoCloseable {
        @WasmExport("echo_string")
        String greet(String name);
    }

    interface ByteProcessor extends AutoCloseable {
        @WasmExport("echo_bytes")
        byte[] process(byte[] input);
    }

    interface StringAnalyzer extends AutoCloseable {
        @WasmExport("string_length")
        int length(String input);
    }

    @Test
    void stringEcho() throws Exception {
        try (Greeter greeter = WasmRuntime.load(Greeter.class, MARSHAL_MODULE)) {
            assertNotNull(greeter);
            String result = greeter.greet("Hello, WebAssembly!");
            assertEquals("Hello, WebAssembly!", result);
        }
    }

    @Test
    void stringEchoUtf8() throws Exception {
        try (Greeter greeter = WasmRuntime.load(Greeter.class, MARSHAL_MODULE)) {
            String result = greeter.greet("\u00e9l\u00e8ve");
            assertEquals("\u00e9l\u00e8ve", result);
        }
    }

    @Test
    void byteArrayEcho() throws Exception {
        try (ByteProcessor processor = WasmRuntime.load(ByteProcessor.class, MARSHAL_MODULE)) {
            assertNotNull(processor);
            byte[] input = {1, 2, 3, 4, 5};
            byte[] result = processor.process(input);
            assertArrayEquals(input, result);
        }
    }

    @Test
    void stringLengthReturnsPrimitive() throws Exception {
        try (StringAnalyzer analyzer = WasmRuntime.load(StringAnalyzer.class, MARSHAL_MODULE)) {
            int len = analyzer.length("hello");
            assertEquals(5, len);
        }
    }

    @Test
    void stringLengthUtf8() throws Exception {
        try (StringAnalyzer analyzer = WasmRuntime.load(StringAnalyzer.class, MARSHAL_MODULE)) {
            // "élève" is 7 UTF-8 bytes
            int len = analyzer.length("\u00e9l\u00e8ve");
            assertEquals(7, len);
        }
    }

}
