[package]
name = "counter_component"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen-rt = { version = "0.36", features = ["bitflags"] }

[package.metadata.component]
package = "tegmentum:test-counter"

[package.metadata.component.target]
path = "wit"
world = "counter-world"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
